version: '3'

services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=credit
    ports:
      - "3307:3306"
  productmicroservice:
    image: productmicroservice
    ports:
        - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/credit?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "./productmicroservice"
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
    restart: always
  customermicroservice:
    image: customermicroservice
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/credit?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "./customermicroservice"
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
    restart: always
  creditmicroservice:
    image: creditmicroservice
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/credit?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "./creditmicroservice"
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
    restart: always